apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ template "mydeployment.fullname" . }}-ping
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ template "mydeployment.fullname" . }}-ping

spec:
  replicas: {{.Values.ping.replicaCount}}
  selector:
    matchLabels:
      app: {{ template "mydeployment.fullname" . }}-ping
      release: {{ .Release.Name }}

  template:
    metadata:
      labels:
        app: {{ template "mydeployment.fullname" . }}-ping
        release: {{ .Release.Name }}
        network-service-id: {{ .Values.global.nsId }}
        type: ping
      annotations:
        k8s.v1.cni.cncf.io/networks: '[{"name": {{ template "mydeployment.fullnameQuoted" . }},
                                        "namespace": {{ .Values.global.namespace | quote }}}]'
        {{- if .Values.ping.metrics.enabled }}
        prometheus.io/scrape: {{ .Values.ping.metrics.annotations.scrape | quote }}
        prometheus.io/path: {{.Values.ping.metrics.annotations.path }}
        prometheus.io/port: {{.Values.ping.metrics.annotations.port | quote}}
        {{- end }}
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: network-service-id
                operator: In
                values:
                - {{ .Values.global.nsId }}
              - key: type
                operator: In
                values:
                - pong
            topologyKey: kubernetes.io/hostname
      {{- with .Values.ping.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.ping.image.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ template "mydeployment.fullname" . }}
        image: {{ .Values.ping.image.repository -}} : {{- .Values.ping.image.tag }}
        imagePullPolicy: {{ .Values.ping.image.pullPolicy }}
