apiVersion: v1
kind: Service
metadata:
  name: {{ template "mydeployment.fullname" . }}-ping
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: {{ template "mydeployment.fullname" . }}-ping
  type: {{ .Values.ping.serviceType }}
  ports:
    - protocol: TCP
      port: 18888
      targetPort: 18888
