apiVersion: v1
kind: Service
metadata:
  name: {{ template "mydeployment.fullname" . }}-pong
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: {{ template "mydeployment.fullname" . }}-pong
  type: {{ .Values.pong.serviceType }}
  ports:
    - protocol: TCP
      port: 18889
      targetPort: 18889
