apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: {{ template "mydeployment.fullname" . }}
  namespace: {{ .Values.global.namespace }}
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": {{ .Values.internalVldInterface | quote }},
      "mode": "bridge",
      "ipam": {
        "type": "host-local",
        "subnet": "192.168.234.0/24",
        "rangeStart": "192.168.234.200",
        "rangeEnd": "192.168.234.216",
        "routes": [
          { "dst": "0.0.0.0/0" }
        ],
        "gateway": "192.168.234.1"
      }
    }'
