apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ template "mydeployment.fullname" . }}-pong
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ template "mydeployment.fullname" . }}-pong

spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "mydeployment.fullname" . }}-pong
      release: {{ .Release.Name }}

  template:
    metadata:
      labels:
        app: {{ template "mydeployment.fullname" . }}-pong
        release: {{ .Release.Name }}
        network-service-id: {{ .Values.global.nsId}}
        type: pong
      annotations:
        k8s.v1.cni.cncf.io/networks: '[{"name": {{ template "mydeployment.fullnameQuoted" . }},
                                        "namespace": {{ .Values.global.namespace | quote }}}]'
        {{- if .Values.pong.metrics.enabled }}
        prometheus.io/scrape: {{ .Values.pong.metrics.annotations.scrape | quote}}
        prometheus.io/path: {{.Values.pong.metrics.annotations.path }}
        prometheus.io/port: {{.Values.pong.metrics.annotations.port | quote}}
        {{- end }}
    spec:
      {{- with .Values.pong.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.pong.image.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ template "mydeployment.fullname" . }}
        image: {{ .Values.pong.image.repository -}} : {{- .Values.pong.image.tag }}
        imagePullPolicy: {{ .Values.pong.image.pullPolicy }}
      {{- with .Values.pong.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
