# Default values for ping
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  # Namespace to deploy the service
  namespace: default
  # ID of NS used to deploy this chart
  nsId: test

# Interface for internal network
internalVldInterface: net1

ping:
  # Number of pods for the service
  replicaCount: 1
  # Service type
  serviceType: NodePort
  image:
    # Image path
    repository: artifactory.riftio.com/docker/rw.ping
    # Image tag
    tag: "2004"
    # Image pull policy
    pullPolicy: IfNotPresent
    # Image secrets, if any
    imagePullSecrets: []
  # Metrics support
  metrics:
    enabled: true
    annotations:
      {
        scrape: true,
        path: /api/v1/ping/metrics,
        port: 18888
      }

pong:
  # Number of pods for the service
  replicaCount: 1
  # Service type
  serviceType: LoadBalancer
  image:
    # Image path
    repository: artifactory.riftio.com/docker/rw.pong
    # Image tag
    tag: "2005"
    # Image pull policy
    pullPolicy: IfNotPresent
    # Image secrets, if any
    imagePullSecrets: []
  # Metrics support
  metrics:
    enabled: true
    annotations:
      {
        scrape: true,
        path: /api/v1/pong/metrics,
        port: 18889
      }
